# Generated by Django 5.0.4 on 2024-04-28 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('all_price', models.PositiveIntegerField()),
                ('clients', models.ManyToManyField(to='fitnes_club.client')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClubCard',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('end_date', models.DateField()),
                ('discount', models.PositiveSmallIntegerField()),
                ('club_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fitnes_club.client')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('description', models.TextField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fitnes_club.group')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.PositiveIntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitnes_club.group')),
                ('halls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitnes_club.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=30)),
                ('workouts', models.ManyToManyField(to='fitnes_club.workout')),
            ],
        ),
    ]
