# Generated by Django 5.0.4 on 2024-04-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubcard',
            old_name='club_card',
            new_name='client',
        ),
    ]
