# Generated by Django 5.0.4 on 2024-05-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0002_rename_club_card_clubcard_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorSchedule',
            fields=[
                ('description', models.TextField()),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fitnes_club.instructor')),
            ],
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='GroupSchedule',
        ),
    ]
