# Generated by Django 5.0.4 on 2024-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0004_client_user_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='about',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(default='', upload_to='instructors_photo'),
        ),
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.CharField(default='Category1', max_length=100),
        ),
    ]
