# Generated by Django 5.0.4 on 2024-05-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0005_instructor_about_instructor_photo_workout_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='halls',
            new_name='hall',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(default='', upload_to='instructors_photo/'),
        ),
    ]
