# Generated by Django 5.0.4 on 2024-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0006_rename_halls_workout_hall_alter_instructor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='expenses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='is_edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='max_clients',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='group',
            name='max_workouts',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
