# Generated by Django 5.0.4 on 2024-05-09 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0008_alter_client_expenses_alter_group_all_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 49, 25, 718045)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clubcard',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 49, 31, 355889)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubcard',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clubcard',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clubcard',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 50, 8, 359305)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='group',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 50, 20, 594029)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 50, 33, 833934)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 50, 45, 939027)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 50, 54, 280627)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='InstructorSchedule',
        ),
    ]
