# Generated by Django 5.0.4 on 2024-05-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0009_client_create_date_client_create_date_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='clients',
            field=models.ManyToManyField(null=True, to='fitnes_club.client'),
        ),
    ]
