# Generated by Django 5.0.4 on 2024-05-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0011_alter_group_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcard',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitnes_club.client'),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitnes_club.group'),
        ),
    ]
