# Generated by Django 5.0.4 on 2024-09-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0013_alter_group_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date_local', models.DateTimeField(auto_now=True)),
                ('update_date_local', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='', upload_to='instructors_photo/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
