# Generated by Django 5.0.4 on 2024-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0014_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(default='https://adrenalin-fitness.by/'),
        ),
    ]
