# Generated by Django 5.0.4 on 2024-09-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0015_remove_partner_name_partner_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='photo',
            new_name='logo',
        ),
    ]
