# Generated by Django 5.0.4 on 2024-09-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnes_club', '0016_rename_photo_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(default='', upload_to='partners_logo/'),
        ),
    ]
