# Generated by Django 5.0.4 on 2024-04-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
    ]
