# Generated by Django 5.0.4 on 2024-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_tasks', '0002_rename_coupons_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default='2024-04-29 10:00'),
            preserve_default=False,
        ),
    ]
