# Generated by Django 5.0.4 on 2024-04-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_tasks', '0003_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='date',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
