# Generated by Django 5.0.4 on 2024-04-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_tasks', '0005_employee_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='Proger', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=40),
        ),
    ]
