# Generated by Django 5.0.4 on 2024-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_tasks', '0006_vacancy_name_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='', upload_to='article_picture'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to='employee_photo'),
        ),
    ]
