# Generated by Django 5.0.4 on 2024-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_tasks', '0008_coupon_discount_alter_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
