# Generated by Django 5.0.4 on 2024-05-09 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_tasks', '0010_basemodel_create_date_local_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 48, 27, 396287)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 48, 37, 857834)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 48, 54, 205646)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 49, 0, 335470)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 49, 5, 663949)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 9, 19, 49, 18, 292240)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='create_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='update_date_local',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
